version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: development_password
      POSTGRES_DB: helpdesk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: